# Generated by Django 4.2.4 on 2023-08-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("ulr", models.CharField(max_length=240)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("clicks", models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
